version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: flask-url-shortener
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
